name: Open Telegram Chat (Astana UTC+5)

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch: {}

jobs:
  open_chat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Show config
        run: cat config.json
      - name: Open chat
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: python bot.py open
